# Generated by Django 4.2.7 on 2025-11-05 08:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not-started', 'Not Started'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired')], default='not-started', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
                ('passed', models.BooleanField(default=False)),
                ('time_taken', models.IntegerField(default=0, help_text='Time in seconds')),
                ('attempt_number', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='skill_assessments.skillcategory')),
            ],
            options={
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20)),
                ('estimated_time', models.IntegerField(help_text='Estimated time in minutes')),
                ('passing_score', models.IntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('badge_image', models.ImageField(blank=True, null=True, upload_to='skill_badges/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_sets', to='skill_assessments.skillcategory')),
                ('prerequisites', models.ManyToManyField(blank=True, to='skill_assessments.skillset')),
            ],
            options={
                'ordering': ['category', 'difficulty_level'],
            },
        ),
        migrations.CreateModel(
            name='UserSkillBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('verification_code', models.CharField(max_length=100, unique=True)),
                ('is_public', models.BooleanField(default=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill_assessments.skillassessment')),
                ('skill_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill_assessments.skillset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identified_weaknesses', models.JSONField(default=list)),
                ('recommended_resources', models.JSONField(default=list)),
                ('improvement_plan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill_assessments.skillassessment')),
                ('skill_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill_assessments.skillset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='skillassessment',
            name='skill_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill_assessments.skillset'),
        ),
        migrations.AddField(
            model_name='skillassessment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PeerComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_score', models.FloatField()),
                ('peer_average', models.FloatField()),
                ('percentile', models.FloatField()),
                ('industry_average', models.FloatField(blank=True, null=True)),
                ('comparison_date', models.DateField(auto_now_add=True)),
                ('total_peers', models.IntegerField(default=0)),
                ('skill_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill_assessments.skillset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_comparisons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-comparison_date'],
            },
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('resource_type', models.CharField(choices=[('course', 'Online Course'), ('tutorial', 'Tutorial'), ('video', 'Video'), ('book', 'Book'), ('article', 'Article'), ('practice', 'Practice Platform'), ('documentation', 'Documentation')], max_length=20)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('provider', models.CharField(max_length=200)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20)),
                ('estimated_duration', models.CharField(max_length=100)),
                ('is_free', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='resource_thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='skill_assessments.skillset')),
            ],
            options={
                'ordering': ['-rating', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('coding', 'Coding Challenge'), ('true-false', 'True/False'), ('fill-blank', 'Fill in the Blank'), ('practical', 'Practical Task')], max_length=20)),
                ('question_text', models.TextField()),
                ('code_snippet', models.TextField(blank=True)),
                ('expected_output', models.TextField(blank=True)),
                ('time_limit', models.IntegerField(default=300, help_text='Time in seconds')),
                ('points', models.IntegerField(default=10)),
                ('difficulty_weight', models.FloatField(default=1.0)),
                ('explanation', models.TextField(blank=True)),
                ('hints', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='skill_assessments.skillset')),
            ],
            options={
                'ordering': ['skill_set', 'question_type'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('explanation', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='skill_assessments.assessmentquestion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True)),
                ('code_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('points_earned', models.IntegerField(default=0)),
                ('time_taken', models.IntegerField(default=0)),
                ('feedback', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='skill_assessments.skillassessment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill_assessments.assessmentquestion')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skill_assessments.assessmentoption')),
            ],
            options={
                'ordering': ['answered_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='skillassessment',
            unique_together={('user', 'skill_set', 'attempt_number')},
        ),
    ]
