# Generated by Django 4.2.7 on 2025-11-05 08:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('growth_rate', models.FloatField(default=0.0)),
                ('total_jobs', models.IntegerField(default=0)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('parent_industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_industries', to='labor_market.industry')),
            ],
            options={
                'verbose_name_plural': 'Industries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('alternate_titles', models.JSONField(default=list)),
                ('required_skills', models.JSONField(default=list)),
                ('preferred_skills', models.JSONField(default=list)),
                ('education_requirements', models.JSONField(default=list)),
                ('experience_level', models.CharField(max_length=50)),
                ('remote_friendly', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_roles', to='labor_market.industry')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SkillDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('job_postings_count', models.IntegerField(default=0)),
                ('growth_rate', models.FloatField(default=0.0)),
                ('avg_salary_premium', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('trending_rank', models.IntegerField(default=0)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('last_updated', models.DateField()),
                ('related_jobs', models.ManyToManyField(related_name='skill_demands', to='labor_market.jobrole')),
            ],
            options={
                'ordering': ['trending_rank'],
            },
        ),
        migrations.CreateModel(
            name='JobMarketTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_type', models.CharField(choices=[('demand', 'Job Demand'), ('salary', 'Salary Trend'), ('skill', 'Skill Demand'), ('automation', 'Automation Risk')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('trend_value', models.FloatField()),
                ('growth_rate', models.FloatField()),
                ('trend_direction', models.CharField(max_length=20)),
                ('confidence_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('data_points', models.JSONField(default=list)),
                ('insights', models.TextField()),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_trends', to='labor_market.jobrole')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='EmergingRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('emergence_score', models.FloatField()),
                ('growth_projection', models.FloatField()),
                ('required_skills', models.JSONField(default=list)),
                ('avg_salary_range', models.CharField(max_length=100)),
                ('identified_date', models.DateField(auto_now_add=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor_market.industry')),
                ('related_roles', models.ManyToManyField(related_name='emerging_alternatives', to='labor_market.jobrole')),
            ],
            options={
                'ordering': ['-emergence_score'],
            },
        ),
        migrations.CreateModel(
            name='CompanyInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_size', models.CharField(choices=[('startup', '1-50'), ('small', '51-200'), ('medium', '201-1000'), ('large', '1001-5000'), ('enterprise', '5000+')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True)),
                ('active_job_openings', models.IntegerField(default=0)),
                ('hiring_trend', models.CharField(max_length=20)),
                ('popular_roles', models.JSONField(default=list)),
                ('employee_satisfaction', models.FloatField(blank=True, null=True)),
                ('growth_stage', models.CharField(blank=True, max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor_market.industry')),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='CareerPathRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField()),
                ('skill_gap_analysis', models.JSONField(default=dict)),
                ('estimated_transition_time', models.CharField(max_length=100)),
                ('salary_potential', models.CharField(max_length=100)),
                ('market_demand_score', models.FloatField()),
                ('reasoning', models.TextField()),
                ('recommended_courses', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('current_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_recommendations', to='labor_market.jobrole')),
                ('recommended_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_recommendations', to='labor_market.jobrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-match_score'],
            },
        ),
        migrations.CreateModel(
            name='SalaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('median_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('avg_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('experience_level', models.CharField(max_length=50)),
                ('data_source', models.CharField(max_length=200)),
                ('last_updated', models.DateField()),
                ('sample_size', models.IntegerField(default=0)),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_data', to='labor_market.jobrole')),
            ],
            options={
                'ordering': ['-last_updated'],
                'unique_together': {('job_role', 'country', 'state', 'city', 'experience_level')},
            },
        ),
    ]
